# Generated by Django 4.2.5 on 2023-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_tieroptions_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tieroptions",
            name="name",
            field=models.CharField(default="custom height", max_length=200),
        ),
    ]
