# Generated by Django 4.2.5 on 2023-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="thumbnail_link",
            field=models.ManyToManyField(null=True, to="images.imagevariant"),
        ),
    ]
