# Generated by Django 4.2.5 on 2023-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_imagevariant_image_thumbnail_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="thumbnail_link",
            field=models.ManyToManyField(to="images.imagevariant"),
        ),
    ]
