# Generated by Django 4.2.5 on 2023-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_alter_imagevariant_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="thumbnail_link",
            field=models.ManyToManyField(blank=True, to="images.imagevariant"),
        ),
    ]
