# Generated by Django 4.2.5 on 2023-10-02 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0003_rename_originally_uploaded_image_tier_allow_originally_size_image",
        ),
        ("images", "0007_rename_url_imagevariant_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="seconds",
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name="imagevariant",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.tieroptions",
            ),
        ),
    ]
