# Generated by Django 4.2.5 on 2023-10-02 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0009_image_expire_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="seconds",
            field=models.IntegerField(
                default=500,
                validators=[
                    django.core.validators.MinValueValidator(limit_value=300),
                    django.core.validators.MaxValueValidator(limit_value=30000),
                ],
            ),
        ),
    ]
