# Generated by Django 4.2.5 on 2023-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0011_remove_image_expire_after_imagevariant_expire_after_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
