# Generated by Django 4.2.5 on 2023-10-03 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0012_testimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestImage",
        ),
    ]
